### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by sroberts** [central-pa-cowork/meta#4]
Couldn't hurt to put our plans on a shared calendar

**Comment by jglovier** [comment]
:thumbsup:

**Comment by hellohynes** [comment]
I could create a shared Google Calendar. Too bad Slack doesn't integrate with Google Calendars yet.

**Comment by hellohynes** [comment]
I guess one question I have with the calendar is would we share our calendars with appointments anonymized? Or create a separate calendar where we designate days we're unavailable?

Personally I prefer option 1 because it doesn't break my current workflow. All I'd like to see for most people is if I should even ask. If I see most people have Tuesday or Wednesday blocked out as "Busy", then I know not to ask about getting together.

**Comment by jglovier** [comment]
Well what do we hope to actually accomplish with the calendar? We have the repo here for discussion of who is available when, etc. Why not just create a separate calendar (from our own, instead of sharing our calendars with each other) and put the days people will be coworking on that calendar. Then that calendar can be shared with everyone so if somebody wants to see when someone else will be coworking, they can just look at the cowork calendar to check. Then nobody has to worry about their personal appointments being exposed to anyone else, etc.

**Comment by hellohynes** [comment]
Yeah I thought of that. The only problem IMO with that is that it breaks my workflow right now. Using github issues, while not ideal at least gets my message in front of the whole group.

We might be able to achieve this by still using the cowork-planning branch using a Slack channel integration, which I just added.

Also while some of my days are set when I can't cowork, most are flexible. My default option would be 'I'm available unless stated otherwise' versus 'I'm unavailable unless stated otherwise.' My calendar isn't so crowded that I need to specify free times vs. busy times.

**Comment by sroberts** [comment]
Ehh I was mostly just trying to throw up a quick issue to keep my contrib graph streak alive.... :wink: 

I guess no good reason to break the current system, and it does seem to be working. Was just thinking that we're trying to represent future temporal and geographic location, and a calendar seems to be the usual preferred method for that
